=== resonite-modding-group/resonite-mod-manifest/schemas/mod-schema.json
{
	"$id": "https://github.com/resonite-modding-group/resonite-mod-manifest/blob/master/schemas/mod-schema.json",
	"$schema": "https://json-schema.org/draft/2020-12/schema",
	"type": "object",
	"properties": {
		"name": {
			"type": "string",
			"description":"Name of the mod"
		},
		"id": {
			"type": "string",
			"description":"id of your mod, typically a reverse domain name followed by the name of the mod"
		},
		"description": {
			"type": "string",
			"description":"Brief description of your mod"
		},
		"category": {
			"type": "string",
			"description":"Category of your mod, if unsure, use Misc",
			"enum": [
				"Asset Importing",
				"Audio",
				"Bug Workaround",
				"Context Menu",
				"Controls",
				"Dashboard",
				"Hardware Integration",
				"Inspectors",
				"Libraries",
				"Memes",
				"Misc",
				"Optimization",
				"Plugins",
				"Protoflux",
				"Technical Tweaks",
				"Template",
				"Visual Tweaks",
				"Wizards"
			]
		},
		"sourceLocation": {
			"type": "string",
			"description":"Where the source of this mod can be found",
			"format": "uri"
		},
		"website": {
			"type": "string",
			"description":"Website or page for this specific mod if it is different than the sourceLocation",
			"format": "uri"
		},
		"tags": {
			"type": "array",
			"description":"Keywords to assist in searching for this mod",
			"items": {
				"type": "string"
			},
			"additionalItems": false
		},
		"flags": {
			"type": "array",
			"items": {
				"type": "string",
				"enum": ["broken", "deprecated", "file", "plugin"]
			},
			"additionalItems": false
		},
		"platforms": {
			"type": "array",
			"description":"Specifically supported platforms if a mod isn't expected to generally run on most platforms",
			"items": {
				"type": "string",
				"enum": ["android", "headless", "linux", "linux-native", "linux-wine", "windows", "other"]
			},
			"additionalItems": false
		},
		"additionalAuthors": {
			"type": "array",
			"description":"Additional authors or significant contributors aside from the main author",
			"items": {
				"type": "string"
			},
			"additionalItems": true
		},
		"versions": {
			"type": "object",
			"minProperties": 1,
			"propertyNames": {
				"pattern": "^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?$"
			},
			"additionalProperties": {
				"type": "object",
				"additionalProperties": false,
				"required": [
					"artifacts"
				],
				"properties": {
					"changelog": {
						"type": "string",
						"description":"Brief description of changes or fixes made"
					},
					"releaseUrl": {
						"type": "string",
						"description": "Link for this specific release",
						"format": "uri"
					},
					"conflicts": {
						"type": "object",
						"description": "Mod ids that are known to conflict with this mod",
						"additionalProperties": {
							"type": "object",
							"required": [
								"version"
							],
							"properties": {
								"version": {
									"type": "string",
									"description":"Versions that conflict, use * for all versions"
								}
							}
						}
					},
					"dependencies": {
						"type": "object",
						"description": "Other mods/libraries that this mod uses",
						"additionalProperties": {
							"type": "object",
							"required": [
								"version"
							],
							"properties": {
								"optional": {
									"type": "boolean",
									"default": false,
									"description": "Marks this dependency as optional. When set, the mod can function without it but may provide additional features or compatibility when available"
								},
								"version": {
									"type": "string",
									"description":"Minimum version required of this dependency"
								}
							}
						}
					},
					"artifacts": {
						"type": "array",
						"description":"All the files for this mod",
						"items": {
							"type": "object",
							"required": [
								"url",
								"sha256"
							],
							"properties": {
								"url": {
									"type": "string",
									"description":"Direct download url of the artifact",
									"format": "uri"
								},
								"filename": {
									"type": "string",
									"description":"Optional name override when saving the artifact",
									"pattern": "^\\S(?:.*\\S)?$"
								},
								"sha256": {
									"type": "string",
									"description":"Sha256 hash of the artifact",
									"pattern": "^[a-fA-F0-9]{64}$"
								},
								"installLocation": {
									"type": "string",
									"default": "/rml_mods",
									"description":"Target install path for the artifact. Defaults to `/rml_mods`. The root path `/` refers to the Resonite installation folder"
								}
							},
							"additionalProperties": false
						},
						"minItems": 1
					}
				}
			}
		}
	},
	"additionalProperties": false,
	"required": [
		"name",
		"id",
		"description",
		"category",
		"versions"
	]
}

=== resonite-modding-group/resonite-mod-manifest/manifest/owo.Nytra/PluginSelect/info.json
{
	"name": "PluginSelect",
	"id": "owo.Nytra.PluginSelect",
	"description": "Adds some extra UI to the \"Start Custom Session\" dialog to allow you to select which data model plugins to use for that session.",
	"category": "Plugins",
	"sourceLocation": "https://github.com/Nytra/ResonitePluginSelect",
	"versions": {
		"1.0.1": {
			"releaseUrl": "https://github.com/Nytra/ResonitePluginSelect/releases/tag/v1.0.1",
			"artifacts": [{
				"url": "https://github.com/Nytra/ResonitePluginSelect/releases/download/v1.0.1/PluginSelect.dll",
				"sha256": "a8d2b95c9950e3d08595573bb52aa5d307536aab13bac23cd1ba61f923b149f1"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/com.nekometer.esnya/EsnyaTweaks/info.json
{
	"name": "EsnyaTweaks",
	"id": "com.nekometer.esnya.EsnyaTweaks",
	"description": "Small tweaks collection for ResoniteModLoader, including While/AsyncWhile timeouts and inspector enhancements.",
	"category": "Technical Tweaks",
	"sourceLocation": "https://github.com/esnya/ResoniteEsnyaTweaks",
	"tags": [
		"PhotonDust",
		"LOD",
		"SystemHelper"
	],
	"versions": {
		"0.1.0": {
			"releaseUrl": "https://github.com/esnya/ResoniteEsnyaTweaks/releases/tag/v0.1.0.0",
			"artifacts": [{
				"url": "https://github.com/esnya/ResoniteEsnyaTweaks/releases/download/v0.1.0.0/EsnyaTweaks.dll",
				"sha256": "54634a157f809dd1b690794e536adf8e4c9613b0d80bd580eaa844e17a0f2fa0"
			}]
		},
		"0.0.1": {
			"releaseUrl": "https://github.com/esnya/ResoniteEsnyaTweaks/releases/tag/v0.0.1.0",
			"artifacts": [{
				"url": "https://github.com/esnya/ResoniteEsnyaTweaks/releases/download/v0.0.1.0/EsnyaTweaks.dll",
				"sha256": "2118994148863950294cae7b361496919b1819ddb8446fbffbc448033d0e1d7a"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/ErrorJan/IgnoreControllerAxis/info.json
{
	"name": "IgnoreControllerAxis",
	"id": "ErrorJan.IgnoreControllerAxis",
	"description": "Make some joystick axis' not react at all or add a custom per axis deadzone.",
	"category": "Controls",
	"sourceLocation": "https://github.com/ErrorJan/ResoniteMod-IgnoreControllerAxis",
	"versions": {
		"1.0.0": {
			"releaseUrl": "https://github.com/ErrorJan/ResoniteMod-IgnoreControllerAxis/releases/tag/1.0.0",
			"artifacts": [{
				"url": "https://github.com/ErrorJan/ResoniteMod-IgnoreControllerAxis/releases/download/1.0.0/IgnoreControllerAxis.dll",
				"sha256": "a4f43339b5bad47d7c53a1e22ba1d6d3791faa8201dfcbce1485e3ca4e43f562"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/net.deltawolf/Fish/info.json
{
	"name": "Fish",
	"id": "net.deltawolf.Fish",
	"description": "You know what that means",
	"category": "Memes",
	"sourceLocation": "https://github.com/XDelta/ResoniteFish",
	"versions": {
		"1.0.0": {
			"releaseUrl": "https://github.com/XDelta/ResoniteFish/releases/tag/1.0.0",
			"artifacts": [{
				"url": "https://github.com/XDelta/ResoniteFish/releases/download/1.0.0/ResoniteFish.dll",
				"filename": "Fish.dll",
				"sha256": "93ffabce687b6307720a724613d6e183a850b49c84221422f419bd05907bbed5"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/ShowDelegates/info.json
{
    "name": "ShowDelegates",
    "id": "me.art0007i.ShowDelegates",
    "description": "Shows delegates and hidden items in the inspector panel",
    "category": "Inspectors",
    "sourceLocation": "https://github.com/art0007i/ShowDelegates",
    "versions": {
        "2.2.4": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.4",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.4/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "b15f241bb31378077cf76c03f5cbdab6f882cad19d0738cc981c91e9be546aac"
                }
            ]
        },
        "2.2.5": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.5",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.5/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "ec2460b109f04c62045c0b537cf50b1e545b72f3aabb6f5e2a3b2320d1b55316"
                }
            ],
            "changelog": "Fix issue where some delegates were not showing up (#7)"
        },
        "2.2.6": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.6",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.6/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "3126895a622ae75bed335d5fe6ee2d1d9ecb4a13179791211464c4f5e4cd85a4"
                }
            ],
            "changelog": "Rebuilt for new resonite version"
        },
        "2.2.7": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.7",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.7/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "3a13bb871d3957bc0a0d956494e8805e9e0686a8233a82bb15a4f7b82d4a0846"
                }
            ],
            "changelog": "Fixed the mod not working in the latest version"
        },
        "2.2.8": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.8",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.8/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "489ccc8326e7b5404be15d874da950772180b3a220bbebcd9cc555079e3041c7"
                }
            ]
        },
        "2.2.9": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.9",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.9/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "420341da08088da831d17d48db53efaf988480820554e52914b69bc4001637d8"
                }
            ],
            "changelog": "Add a few delegates to the lookup table"
        },
        "2.2.10": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.10",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.10/ShowDelegates.dll",
                    "filename": "ShowDelegates.dll",
                    "sha256": "b35b1a6893617c3cdf5a976c99f4d8a17f1770cfe6e8136515043c91f908afa2"
                }
            ],
            "changelog": "Fix for splittening"
        },
        "2.2.11": {
            "releaseUrl": "https://github.com/art0007i/ShowDelegates/releases/tag/2.2.11",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/ShowDelegates/releases/download/2.2.11/ShowDelegates.dll",
                    "sha256": "8aebd1cf051c235f43bad2cd902099e46c194dfd097729267b70cc9fcf0d48d4"
                }
            ],
            "changelog": "Gracefully handle errors when the type stored in the sync method attribute is wrong"
        }
    }
}

=== resonite-modding-group/resonite-mod-manifest/manifest/net.hantabaru1014/HeadCullingMask/info.json
{
	"name": "HeadCullingMask",
	"id": "net.hantabaru1014.HeadCullingMask",
	"description": "Make your avatar's head invisible only to your FPV",
	"category": "Visual Tweaks",
	"sourceLocation": "https://github.com/hantabaru1014/HeadCullingMask",
	"versions": {
		"2.0.0": {
			"releaseUrl": "https://github.com/hantabaru1014/HeadCullingMask/releases/tag/v2.0.0",
			"artifacts": [{
				"url": "https://github.com/hantabaru1014/HeadCullingMask/releases/download/v2.0.0/HeadCullingMask.dll",
				"sha256": "d621b87e4bec4806cfd164ee56f8b44f9c972adecba70561cb7a48e08b77ddc8"
			}]
		}
	}
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/MyInspectors/info.json
{
    "versions": {
        "2.0.1": {
            "releaseUrl": "https://github.com/art0007i/MyInspectors/releases/tag/2.0.1",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/MyInspectors/releases/download/2.0.1/MyInspectors.dll",
                    "filename": "MyInspectors.dll",
                    "sha256": "da60f1bc535a5054124e2f746a0f3df90a7a19d87e132e25a5084034b9a1c24f"
                }
            ],
            "changelog": "Fixed for new resonite version"
        },
        "2.0.2": {
            "releaseUrl": "https://github.com/art0007i/MyInspectors/releases/tag/2.0.2",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/MyInspectors/releases/download/2.0.2/MyInspectors.dll",
                    "filename": "MyInspectors.dll",
                    "sha256": "048818e89f8a5b63d64047bb2fa717c4f3e16b7affdd96d2dc15dafda857fbcb"
                }
            ],
            "changelog": "Add toggle on/off option"
        },
        "2.0.3": {
            "releaseUrl": "https://github.com/art0007i/MyInspectors/releases/tag/2.0.3",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/MyInspectors/releases/download/2.0.3/MyInspectors.dll",
                    "filename": "MyInspectors.dll",
                    "sha256": "fe34c3a1a364e000962ca60d496d94caf0c81b73fd64d958233260e53f0b4f78"
                }
            ],
            "changelog": "Fix for splittening"
        }
    },
    "name": "MyInspectors",
    "id": "me.art0007i.MyInspectors",
    "description": "Makes inspectors generate by local user instead of host. Slightly unsable, if anything with inspectors breaks remove this mod.",
    "category": "Inspectors",
    "sourceLocation": "https://github.com/art0007i/MyInspectors"
}

=== resonite-modding-group/resonite-mod-manifest/manifest/me.art0007i/QuickFolderOpener/info.json
{
    "name": "QuickFolderOpener",
    "id": "me.art0007i.QuickFolderOpener",
    "description": "Adds an option to your context menu which can open a folder without saving it",
    "category": "Misc",
    "sourceLocation": "https://github.com/art0007i/QuickFolderOpener",
    "versions": {
        "2.0.1": {
            "releaseUrl": "https://github.com/art0007i/QuickFolderOpener/releases/tag/2.0.1",
            "artifacts": [
                {
                    "url": "https://github.com/art0007i/QuickFolderOpener/releases/download/2.0.1/QuickFolderOpener.dll",
                    "filename": "QuickFolderOpener.dll",
                    "sha256": "821ceeeeecd1a9e56c117e15f457f517e1e821666464a4d169e27c0be979f3f5"
                }
            ]
        }
    }
}
